emacs ./res/layout/activity_bill_to_menu.xml
emacs ./res/layout/activity_company_list.xml
emacs ./res/layout/activity_create_account.xml
emacs ./res/layout/activity_crmmain_menu.xml
emacs ./res/layout/activity_enter_company.xml
emacs ./res/layout/activity_enter_person.xml
emacs ./res/layout/activity_enter_task.xml
emacs ./res/layout/activity_error.xml
emacs ./res/layout/activity_get_user_list.xml
emacs ./res/layout/activity_list_departments.xml
emacs ./res/layout/activity_list_task_types.xml
emacs ./res/layout/activity_main.xml
emacs ./res/layout/activity_main_menu.xml
emacs ./res/layout/activity_people_list.xml
emacs ./res/layout/activity_pick_date_time.xml
emacs ./res/layout/activity_task_list.xml
emacs ./res/layout/activity_task_list_params.xml
emacs ./res/layout/activity_task_main_menu.xml
emacs ./res/layout/enter_company_item.xml
emacs ./res/layout/enter_person_item.xml
emacs ./res/layout/enter_task_item.xml
emacs ./res/layout/enter_task_type_item.xml
emacs ./res/layout/list_company_item.xml
emacs ./res/layout/list_person_item.xml
emacs ./res/layout/list_task_item.xml
emacs ./res/layout/list_task_type_item.xml
